"""Phase A #09 — Daily email recap.

Generates an HTML summary of today's trading (counts, PnL, top
winners/losers, rule adherence highlight) and emits via SMTP. Dry-run
by default; configure via env:

    FIRM_SMTP_HOST, FIRM_SMTP_PORT, FIRM_SMTP_USER, FIRM_SMTP_PASS,
    FIRM_SMTP_FROM, FIRM_SMTP_TO

Usage:
    python scripts/email_recap.py           # dry-run: prints HTML
    python scripts/email_recap.py --send    # actually send
"""
from __future__ import annotations

import argparse
import os
import smtplib
import sys
from datetime import UTC, datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = REPO_ROOT / "reports" / "email_recap.md"
sys.path.insert(0, str(REPO_ROOT / "scripts"))
from _trade_utils import load_trades, summary_stats  # noqa: E402


def _build_html(trades, stats) -> str:
    # color palette matches command center
    header = f"""
    <div style="font-family:-apple-system,Segoe UI,sans-serif;background:#0a0e14;color:#d4d4d4;padding:32px;border-radius:8px;max-width:720px;margin:auto">
      <h1 style="color:#50fa7b;font-weight:300;margin:0 0 8px 0">The Firm · Daily Recap</h1>
      <div style="color:#888;font-size:13px;margin-bottom:24px">{datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}</div>
    """
    kpis = f"""
      <table style="width:100%;border-collapse:collapse;margin-bottom:24px">
        <tr>
          <td style="padding:12px;border:1px solid #222;width:25%"><div style="color:#888;font-size:11px;text-transform:uppercase">Trades</div><div style="font-size:22px;color:#d4d4d4;font-family:monospace">{stats['n']}</div></td>
          <td style="padding:12px;border:1px solid #222;width:25%"><div style="color:#888;font-size:11px;text-transform:uppercase">Win rate</div><div style="font-size:22px;color:#50fa7b;font-family:monospace">{stats['win_rate']:.1%}</div></td>
          <td style="padding:12px;border:1px solid #222;width:25%"><div style="color:#888;font-size:11px;text-transform:uppercase">PF</div><div style="font-size:22px;color:#d4d4d4;font-family:monospace">{stats['profit_factor']:.2f}</div></td>
          <td style="padding:12px;border:1px solid #222;width:25%"><div style="color:#888;font-size:11px;text-transform:uppercase">PnL</div><div style="font-size:22px;color:{'#50fa7b' if stats['total_pnl'] >= 0 else '#ff5555'};font-family:monospace">${stats['total_pnl']:+.2f}</div></td>
        </tr>
      </table>
    """
    rows = []
    for t in trades[:20]:
        color = "#50fa7b" if t.net_pnl > 0 else "#ff5555" if t.net_pnl < 0 else "#888"
        when = t.exit_ts.strftime("%H:%M:%S") if t.exit_ts else "—"
        rows.append(
            f"<tr>"
            f"<td style='padding:6px;border-bottom:1px solid #1a1a1a;font-family:monospace;font-size:12px'>{when}</td>"
            f"<td style='padding:6px;border-bottom:1px solid #1a1a1a'>{t.side}</td>"
            f"<td style='padding:6px;border-bottom:1px solid #1a1a1a;text-align:right;font-family:monospace'>{t.qty}</td>"
            f"<td style='padding:6px;border-bottom:1px solid #1a1a1a;text-align:right;font-family:monospace;color:{color}'>${t.net_pnl:+.2f}</td>"
            f"<td style='padding:6px;border-bottom:1px solid #1a1a1a;text-align:right;font-family:monospace;color:{color}'>{t.r_multiple:+.2f}R</td>"
            f"</tr>"
        )
    recent = f"""
      <h2 style="color:#50fa7b;font-weight:300;font-size:14px;margin-bottom:8px">Recent trades</h2>
      <table style="width:100%;border-collapse:collapse;font-size:12px;margin-bottom:24px">
        <thead><tr style="color:#888">
          <th style="text-align:left;padding:6px;border-bottom:1px solid #222">Time</th>
          <th style="text-align:left;padding:6px;border-bottom:1px solid #222">Side</th>
          <th style="text-align:right;padding:6px;border-bottom:1px solid #222">Qty</th>
          <th style="text-align:right;padding:6px;border-bottom:1px solid #222">PnL</th>
          <th style="text-align:right;padding:6px;border-bottom:1px solid #222">R</th>
        </tr></thead>
        <tbody>{"".join(rows)}</tbody>
      </table>
    """
    footer = """
      <div style="color:#666;font-size:11px;padding-top:16px;border-top:1px solid #222">
        Auto-generated by <code>scripts/email_recap.py</code>. The Firm · MNQ futures automation.
      </div>
    </div>
    """
    return header + kpis + recent + footer


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--send", action="store_true", help="Actually send (requires SMTP env vars)")
    p.add_argument("--subject", default=None)
    args = p.parse_args()

    trades = load_trades()
    stats = summary_stats(trades)
    html = _build_html(trades[-30:], stats) if trades else (
        '<p style="font-family:monospace">No trades in journal.</p>'
    )
    subject = args.subject or f"[The Firm] Daily recap · {stats['n']} trades · ${stats['total_pnl']:+.2f}"
    send_status = "dry-run (use --send + FIRM_SMTP_* to actually send)"

    if args.send:
        host = os.environ.get("FIRM_SMTP_HOST", "")
        port = int(os.environ.get("FIRM_SMTP_PORT", "465"))
        user = os.environ.get("FIRM_SMTP_USER", "")
        pwd = os.environ.get("FIRM_SMTP_PASS", "")
        frm = os.environ.get("FIRM_SMTP_FROM", user)
        to = os.environ.get("FIRM_SMTP_TO", "")
        if not (host and user and pwd and to):
            print("[email_recap] missing SMTP env vars; cannot send", file=sys.stderr)
            return 2
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = frm
        msg["To"] = to
        msg.attach(MIMEText(html, "html"))
        try:
            with smtplib.SMTP_SSL(host, port, timeout=20) as s:
                s.login(user, pwd)
                s.sendmail(frm, [to], msg.as_string())
            send_status = f"sent → {to}"
        except Exception as exc:  # noqa: BLE001
            send_status = f"error: {exc}"

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(
        f"# Email recap · {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}\n\n"
        f"- subject: `{subject}`\n- status: `{send_status}`\n- trades: {stats['n']}\n"
        f"- PnL: ${stats['total_pnl']:+.2f}\n\n"
        "## Rendered HTML (preview)\n```html\n" + html[:4000] + "\n...\n```\n"
    )
    print(f"email_recap: {send_status}")
    print(html[:800])
    return 0


if __name__ == "__main__":
    sys.exit(main())
