"""Per-variant regime-expectancy report (v0.2.14).

Iterates every variant in ``scripts.strategy_v2.VARIANTS``, calls
``mnq.spec.runtime_payload.build_spec_payload``, and renders a markdown
table that lets the operator answer:

  * "Which variants have positive expectancy in WHICH regimes?"
  * "Which variants only show edge in regimes with thin sample size?"
  * "Are any variants completely uncalibrated (only stub provenance)?"

The classifier cache (data/cache/regime_per_day.json) is reused across
all variants in a single run, so the full report builds in O(n_variants)
spec_payload calls, each ~0.02s with warm cache.

Usage
-----
    python scripts/regime_report.py
    python scripts/regime_report.py --output reports/custom.md
    python scripts/regime_report.py --variants r4_real_orderflow,r5_real_wide_target
    python scripts/regime_report.py --json  # machine-readable

Exit codes: 0 always (this is a reporter, not a gate).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "src"
SCRIPTS = REPO_ROOT / "scripts"
for p in (SRC, SCRIPTS):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

from mnq.spec.runtime_payload import build_spec_payload  # noqa: E402

DEFAULT_OUTPUT = REPO_ROOT / "reports" / "regime_expectancy.md"

# Canonical order for regime columns. Matches CanonicalRegime.value.
REGIME_COLUMNS = [
    "low-vol-trend", "low-vol-range", "low-vol-reversal",
    "high-vol-trend", "high-vol-range", "high-vol-reversal",
    "crash", "euphoria", "dead-zone", "transition",
]


def _format_cell(stats: dict[str, float] | None) -> str:
    """Format one (variant, regime) cell.

    Returns "-" when no data, else "n=<n_days>/E=<expectancy_r:+.3f>R".
    """
    if not stats:
        return "-"
    n = int(stats.get("n_days", 0))
    e = stats.get("expectancy_r", 0.0)
    if n == 0:
        return "-"
    return f"n={n}/E={e:+.3f}R"


def _render_markdown(rows: list[dict[str, Any]]) -> str:
    """Render the per-variant regime expectancy as a markdown table.

    Variants are rows; regimes are columns. Each cell shows
    n_days / expectancy_r so the operator can scan for edge + evidence
    weight in one pass.
    """
    lines: list[str] = [
        "# Per-variant regime expectancy",
        "",
        "Generated by `scripts/regime_report.py`. Each cell shows ",
        "`n=<days>/E=<expectancy_r>R` -- days the variant traded in ",
        "that regime and the per-trade expectancy in R-multiples. ",
        "`-` means the variant had no trading days in that regime ",
        "in the cached backtest.",
        "",
        "Higher expectancy_r is better; pair it with n_days to gauge ",
        "evidence weight. A variant with E=+1.0R but n=1 is a single ",
        "lucky day, not edge. A variant with E=+0.1R and n=30 is ",
        "calibrated edge.",
        "",
    ]
    # Header
    # v0.2.19: include E_recency column (v0.2.18 recency-weighted) so
    # the operator can spot drift at a glance.
    cols = ["variant", "n_total", "E_total", "E_recency", "drift",
            "provenance", *REGIME_COLUMNS]
    lines.append("| " + " | ".join(cols) + " |")
    lines.append("|" + "|".join(["---"] * len(cols)) + "|")
    for row in rows:
        e_total = row.get("expected_expectancy_r", 0.0)
        e_recency = row.get("recency_weighted_expectancy_r")
        if e_recency is None:
            e_recency_cell = "-"
            drift_cell = "-"
        else:
            e_recency_cell = f"{e_recency:+.3f}R"
            delta = e_recency - e_total
            if abs(delta) < 0.05:
                drift_cell = "STEADY"
            elif delta < 0:
                drift_cell = f"FADING ({delta:+.3f}R)"
            else:
                drift_cell = f"GROWING ({delta:+.3f}R)"
        cells = [
            row["variant"],
            str(row["sample_size"]),
            f"{e_total:+.3f}R",
            e_recency_cell,
            drift_cell,
            ",".join(row["provenance"]) or "-",
        ]
        per_regime = row.get("regime_expectancy", {})
        for regime in REGIME_COLUMNS:
            cells.append(_format_cell(per_regime.get(regime)))
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    # Summary stats
    n_calibrated = sum(
        1 for r in rows if "cached_backtest" in r.get("provenance", [])
    )
    n_real_regimes = sum(
        1 for r in rows
        if any(
            (s.get("expectancy_r", 0.0) > 0.05 and s.get("n_days", 0) >= 5)
            for s in r.get("regime_expectancy", {}).values()
        )
    )
    lines.append("## Summary")
    lines.append("")
    lines.append(f"* Total variants reviewed: **{len(rows)}**")
    lines.append(
        f"* Variants with cached-backtest provenance: **{n_calibrated}**",
    )
    lines.append(
        f"* Variants with at least one regime where E > 0.05R AND "
        f"n_days >= 5 (real edge + thick evidence): **{n_real_regimes}**",
    )
    return "\n".join(lines) + "\n"


def _build_rows(variant_filter: list[str] | None) -> list[dict[str, Any]]:
    """Build one row per variant (filtered by name if provided)."""
    try:
        from strategy_v2 import VARIANTS  # type: ignore
    except ImportError:
        return []
    rows: list[dict[str, Any]] = []
    for cfg in VARIANTS:
        if variant_filter and cfg.name not in variant_filter:
            continue
        payload = build_spec_payload(cfg.name)
        rows.append({
            "variant": cfg.name,
            "sample_size": payload.get("sample_size", 0),
            "expected_expectancy_r": payload.get("expected_expectancy_r", 0.0),
            "recency_weighted_expectancy_r": (
                payload.get("recency_weighted_expectancy_r")
            ),
            "regimes_approved": payload.get("regimes_approved", []),
            "regime_expectancy": payload.get("regime_expectancy", {}),
            "provenance": payload.get("provenance", ["stub"]),
        })
    return rows


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    p.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help=f"output markdown file (default: {DEFAULT_OUTPUT})",
    )
    p.add_argument(
        "--variants", type=str, default=None,
        help="comma-separated list of variant names; default is all",
    )
    p.add_argument(
        "--json", action="store_true",
        help="emit JSON instead of markdown (machine-readable)",
    )
    args = p.parse_args(argv)

    variant_filter: list[str] | None = None
    if args.variants:
        variant_filter = [v.strip() for v in args.variants.split(",") if v.strip()]

    rows = _build_rows(variant_filter)
    if not rows:
        print("no variants resolved (strategy_v2.VARIANTS empty?)", file=sys.stderr)
        return 0

    if args.json:
        print(json.dumps({"variants": rows}, indent=2, default=str))
        return 0

    md = _render_markdown(rows)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(md, encoding="utf-8")
    print(f"wrote {args.output} ({len(rows)} variants)")
    # Echo a one-line summary to stdout
    n_with_evidence = sum(
        1 for r in rows
        if any(
            (s.get("expectancy_r", 0.0) > 0.05 and s.get("n_days", 0) >= 5)
            for s in r.get("regime_expectancy", {}).values()
        )
    )
    print(
        f"summary: {len(rows)} variants, "
        f"{n_with_evidence} with real edge (E > 0.05R AND n_days >= 5)",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
