"""Self-healing guard for the Firm runtime shim.

Background
----------

``src/mnq/firm_runtime.py`` is an auto-generated bridge shim — the only
module in mnq_bot that imports the external ``firm`` package. It is
regenerated by ``scripts/firm_bridge.py --integrate`` from a probe of
the Firm package.

The shim lives inside the OneDrive-synced tree. OneDrive has
(repeatedly — v5, v6, v7, v8, v9) truncated the file mid-function at
byte ~3.5KB, leaving a syntactically broken Python file. The symptom
is a ``SyntaxError`` on import, or — subtler — a silent truncation
where the file parses but the ``run_six_stage_review`` function ends
abruptly without returning.

This module provides ``ensure_firm_runtime_healthy()``: a fast,
side-effect-free check + repair helper. It:

1. ``ast.parse()`` s the shim to verify it's syntactically valid
2. Confirms ``run_six_stage_review`` is defined AND returns
   (i.e., the function body has a ``Return`` node)
3. If either check fails, copies a known-good copy from
   ``upload_bundle/firm-basement-audit/fixes/firm_runtime.py``

The known-good copy lives outside the OneDrive tree and is checked
into the bundle. If it's also missing, ``ensure_firm_runtime_healthy``
raises ``RuntimeError`` with actionable guidance.

Usage
-----

Call this **before** any code path that imports
``mnq.firm_runtime.run_six_stage_review``. Safe to call many times
per process — idempotent, and a no-op when the shim is healthy.

    from mnq._shim_guard import ensure_firm_runtime_healthy
    ensure_firm_runtime_healthy()
    from mnq.firm_runtime import run_six_stage_review  # now safe
"""

from __future__ import annotations

import ast
import logging
import shutil
from pathlib import Path

__all__ = [
    "SHIM_PATH",
    "KNOWN_GOOD_PATH",
    "GUARDED_FILES",
    "ShimHealth",
    "check_shim_health",
    "check_file_health",
    "ensure_firm_runtime_healthy",
    "ensure_file_healthy",
    "heal_all_guarded_files",
]

logger = logging.getLogger(__name__)

# Resolve from this module's own location; survives any CWD.
_HERE = Path(__file__).resolve().parent
SHIM_PATH = _HERE / "firm_runtime.py"

# Known-good copy lives outside the OneDrive tree so it can't be
# truncated by the same sync bug.
_REPO_ROOT = _HERE.parents[1]
_UPLOAD_BUNDLE_CANDIDATES = (
    # In-tree upload bundle (historical v5..v8 lived here)
    _REPO_ROOT.parent / "upload_bundle" / "firm-basement-audit" / "fixes" / "firm_runtime.py",
    # Session-root upload bundle
    _REPO_ROOT.parents[1] / "upload_bundle" / "firm-basement-audit" / "fixes" / "firm_runtime.py"
    if len(_REPO_ROOT.parents) >= 2
    else _REPO_ROOT / "upload_bundle" / "firm-basement-audit" / "fixes" / "firm_runtime.py",
    # Sibling of src/
    _REPO_ROOT / "upload_bundle" / "firm-basement-audit" / "fixes" / "firm_runtime.py",
)

KNOWN_GOOD_PATH: Path | None = next((p for p in _UPLOAD_BUNDLE_CANDIDATES if p.exists()), None)


class ShimHealth:
    """Structured result from a shim health check."""

    __slots__ = ("ok", "reason", "path", "size_bytes")

    def __init__(self, ok: bool, reason: str, path: Path, size_bytes: int):
        self.ok = ok
        self.reason = reason
        self.path = path
        self.size_bytes = size_bytes

    def __repr__(self) -> str:  # pragma: no cover — debug only
        return (
            f"ShimHealth(ok={self.ok}, reason={self.reason!r}, "
            f"path={self.path}, size_bytes={self.size_bytes})"
        )


def check_shim_health(path: Path = SHIM_PATH) -> ShimHealth:
    """Return a ShimHealth describing whether the shim looks intact.

    Four failure modes are detected:

    - File missing
    - File empty
    - File does not parse as Python (SyntaxError)
    - File parses but ``run_six_stage_review`` either is not defined
      or has no ``Return`` statement in its body (truncation case)
    """
    if not path.exists():
        return ShimHealth(False, "missing", path, 0)

    raw = path.read_bytes()
    size = len(raw)
    if size == 0:
        return ShimHealth(False, "empty", path, 0)

    try:
        tree = ast.parse(raw, filename=str(path))
    except SyntaxError as exc:
        return ShimHealth(False, f"syntax_error: {exc.msg}", path, size)

    # Look for run_six_stage_review — either a function or a coroutine.
    target_fn: ast.FunctionDef | ast.AsyncFunctionDef | None = None
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name == "run_six_stage_review":
                target_fn = node
                break

    if target_fn is None:
        return ShimHealth(False, "missing_run_six_stage_review", path, size)

    # The truncation bug leaves a syntactically-valid for-loop body that
    # never reaches the ``return`` statement. Verify the function body
    # contains at least one Return.
    has_return = any(isinstance(n, ast.Return) for n in ast.walk(target_fn))
    if not has_return:
        return ShimHealth(False, "truncated_no_return", path, size)

    return ShimHealth(True, "ok", path, size)


def ensure_firm_runtime_healthy(
    path: Path = SHIM_PATH,
    *,
    known_good: Path | None = None,
    raise_on_failure: bool = True,
) -> ShimHealth:
    """Check the shim; restore from known-good if broken.

    Parameters
    ----------
    path : Path
        Location of the shim. Defaults to ``src/mnq/firm_runtime.py``
        resolved from this module.
    known_good : Path | None
        Override for the known-good source. If None, searches the
        upload_bundle candidates resolved at import time.
    raise_on_failure : bool
        If True (default), raise ``RuntimeError`` when the shim is
        broken AND no known-good source is available. If False, return
        the failed ShimHealth.

    Returns
    -------
    ShimHealth:
        The final health state after any repair attempt. If the shim
        was healthy to begin with, returns that initial health unchanged.
    """
    initial = check_shim_health(path)
    if initial.ok:
        return initial

    source = known_good or KNOWN_GOOD_PATH
    if source is None or not source.exists():
        msg = (
            f"firm_runtime.py is broken ({initial.reason}, {initial.size_bytes} bytes) "
            f"and no known-good copy is available. Searched: "
            f"{[str(p) for p in _UPLOAD_BUNDLE_CANDIDATES]}. "
            f"Re-run scripts/firm_bridge.py --integrate to regenerate, "
            f"or restore manually from a clean bundle."
        )
        if raise_on_failure:
            raise RuntimeError(msg)
        logger.error(msg)
        return initial

    logger.warning(
        "firm_runtime.py is %s (%d bytes). Restoring from %s.",
        initial.reason,
        initial.size_bytes,
        source,
    )
    # Atomic-ish: write to tmp, rename into place.
    tmp = path.with_suffix(".py.repair.tmp")
    shutil.copy2(source, tmp)
    tmp.replace(path)

    final = check_shim_health(path)
    if not final.ok:
        msg = (
            f"Restore from {source} produced an unhealthy shim: {final.reason}. "
            f"The known-good copy may itself be corrupt."
        )
        if raise_on_failure:
            raise RuntimeError(msg)
        logger.error(msg)
    else:
        logger.info("firm_runtime.py successfully restored.")
    return final


# ---------------------------------------------------------------------------
# Generic guard — extends the self-healing pattern beyond firm_runtime.py.
#
# The OneDrive truncation artifact has now hit three files in three different
# batches:
#
#   - src/mnq/firm_runtime.py            (v5..v9, 5 times)
#   - src/mnq/eta_v3/__init__.py        (v9)
#   - src/mnq/eta_v3/meta_adapter.py    (v10, mid-apply_meta_overrides)
#
# The sync bug truncates at ~3.5KB. For each at-risk file we now keep a
# known-good copy in upload_bundle/firm-basement-audit/fixes/, and the
# root conftest calls ``heal_all_guarded_files()`` on every pytest startup.
# ---------------------------------------------------------------------------

_FIXES_DIR_CANDIDATES: tuple[Path, ...] = tuple(
    p
    for p in (
        # Parent of repo (/mnt/upload_bundle/...)
        _REPO_ROOT.parent / "upload_bundle" / "firm-basement-audit" / "fixes",
        # Two levels up — the session-root layout
        # (/sessions/<id>/upload_bundle/...). This is where the real
        # fixes live in the current workspace.
        (_REPO_ROOT.parents[1] if len(_REPO_ROOT.parents) >= 2 else _REPO_ROOT)
        / "upload_bundle"
        / "firm-basement-audit"
        / "fixes",
        # Sibling of src/ (in-tree upload bundle)
        _REPO_ROOT / "upload_bundle" / "firm-basement-audit" / "fixes",
    )
)


def _find_fix(filename: str) -> Path | None:
    """Locate ``<fixes_dir>/<filename>`` across candidate paths."""
    for base in _FIXES_DIR_CANDIDATES:
        p = base / filename
        if p.exists():
            return p
    return None


def _structural_check(
    tree: ast.Module,
    required_symbols: tuple[str, ...],
    required_fn_returns: tuple[str, ...] = (),
) -> str | None:
    """Return a failure reason string, or None if structure looks intact.

    A module is "structurally ok" if:

    - Each of ``required_symbols`` appears as a top-level function /
      async function / class / assignment / AnnAssign target / simple
      import alias.
    - Each of ``required_fn_returns`` names a top-level function whose
      body contains at least one ``Return`` node. This catches the
      truncation case where the function is defined but its body got
      lopped off before the return (the firm_runtime.py pattern).
    """
    defined: set[str] = set()
    fn_nodes: dict[str, ast.FunctionDef | ast.AsyncFunctionDef] = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            defined.add(node.name)
            fn_nodes[node.name] = node
        elif isinstance(node, ast.ClassDef):
            defined.add(node.name)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    defined.add(target.id)
                elif isinstance(target, (ast.Tuple, ast.List)):
                    for elt in target.elts:
                        if isinstance(elt, ast.Name):
                            defined.add(elt.id)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            defined.add(node.target.id)
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            for alias in node.names:
                defined.add(alias.asname or alias.name.split(".")[0])

    missing = [s for s in required_symbols if s not in defined]
    if missing:
        return f"missing_symbols: {','.join(missing)}"

    for fn_name in required_fn_returns:
        fn = fn_nodes.get(fn_name)
        if fn is None:
            return f"missing_function: {fn_name}"
        has_return = any(isinstance(n, ast.Return) for n in ast.walk(fn))
        if not has_return:
            return f"truncated_no_return: {fn_name}"
        # Stronger check: the last top-level statement in the function
        # body must be a Return (or a compound statement that always
        # returns). This catches the case where the function has an
        # early guard return but the main flow got truncated — the
        # exact pattern OneDrive has hit on apply_meta_overrides twice.
        if fn.body:
            last = fn.body[-1]
            if not _ends_with_return(last):
                return f"truncated_body_missing_final_return: {fn_name}"

    return None


def _ends_with_return(node: ast.stmt) -> bool:
    """Does this statement guarantee a Return as its final outcome?

    Conservatively handles: bare Return, If with both branches ending
    in return, Try/With/While/For wrappers whose body ends in return.
    For the truncation case we care about, ``return out`` as the last
    line of the function — a straight ``Return`` node — is enough.
    """
    if isinstance(node, ast.Return):
        return True
    if isinstance(node, ast.If):
        return bool(node.body and _ends_with_return(node.body[-1])) and bool(
            node.orelse and _ends_with_return(node.orelse[-1])
        )
    if isinstance(node, (ast.With, ast.AsyncWith, ast.Try)):
        return bool(node.body and _ends_with_return(node.body[-1]))
    return False


def check_file_health(
    path: Path,
    *,
    required_symbols: tuple[str, ...] = (),
    required_fn_returns: tuple[str, ...] = (),
    min_bytes: int = 0,
) -> ShimHealth:
    """Generic sibling of ``check_shim_health`` for non-shim files.

    Parameters
    ----------
    path : Path
        File to inspect.
    required_symbols : tuple[str, ...]
        Module-level names that MUST exist (functions, classes,
        assignments, or imports). Useful for guarding ``__init__.py``
        re-export lists — if the file was truncated before the last
        import, we catch it here.
    min_bytes : int
        Optional floor on file size. Files under this threshold are
        flagged as ``too_small``; useful when we know a file should
        always be at least N bytes and a smaller version is a sync
        artifact.
    """
    if not path.exists():
        return ShimHealth(False, "missing", path, 0)

    raw = path.read_bytes()
    size = len(raw)
    if size == 0:
        return ShimHealth(False, "empty", path, 0)
    if size < min_bytes:
        return ShimHealth(False, f"too_small: {size} < {min_bytes}", path, size)

    try:
        tree = ast.parse(raw, filename=str(path))
    except SyntaxError as exc:
        return ShimHealth(False, f"syntax_error: {exc.msg}", path, size)

    reason = _structural_check(tree, required_symbols, required_fn_returns)
    if reason is not None:
        return ShimHealth(False, reason, path, size)

    return ShimHealth(True, "ok", path, size)


def ensure_file_healthy(
    path: Path,
    *,
    known_good: Path | None,
    required_symbols: tuple[str, ...] = (),
    required_fn_returns: tuple[str, ...] = (),
    min_bytes: int = 0,
    raise_on_failure: bool = True,
) -> ShimHealth:
    """Generic sibling of ``ensure_firm_runtime_healthy``.

    Uses ``check_file_health`` for the structural check, then falls back
    to the same atomic-write restore pattern.
    """
    initial = check_file_health(
        path,
        required_symbols=required_symbols,
        required_fn_returns=required_fn_returns,
        min_bytes=min_bytes,
    )
    if initial.ok:
        return initial

    if known_good is None or not known_good.exists():
        msg = (
            f"{path.name} is broken ({initial.reason}, "
            f"{initial.size_bytes} bytes) and no known-good copy is "
            f"available."
        )
        if raise_on_failure:
            raise RuntimeError(msg)
        logger.error(msg)
        return initial

    logger.warning(
        "%s is %s (%d bytes). Restoring from %s.",
        path,
        initial.reason,
        initial.size_bytes,
        known_good,
    )
    tmp = path.with_suffix(path.suffix + ".repair.tmp")
    shutil.copy2(known_good, tmp)
    tmp.replace(path)

    final = check_file_health(
        path,
        required_symbols=required_symbols,
        required_fn_returns=required_fn_returns,
        min_bytes=min_bytes,
    )
    if not final.ok:
        msg = (
            f"Restore of {path.name} from {known_good} produced an "
            f"unhealthy file: {final.reason}. The known-good copy may "
            f"itself be corrupt."
        )
        if raise_on_failure:
            raise RuntimeError(msg)
        logger.error(msg)
    else:
        logger.info("%s successfully restored.", path.name)
    return final


# ---- registry of guarded files ---------------------------------------------
#
# Each entry:
#   target_path, known_good_filename_in_fixes_dir,
#   required_symbols_tuple, required_fn_returns_tuple, min_bytes_int
#
# required_symbols is the minimum set of top-level names the module must
# re-export or define. required_fn_returns is the set of top-level
# functions that MUST contain at least one Return node (catches
# mid-function truncation where the body parses but the return got
# lopped off).

GUARDED_FILES: tuple[tuple[Path, str, tuple[str, ...], tuple[str, ...], int], ...] = (
    (
        _HERE / "eta_v3" / "__init__.py",
        "eta_v3_init.py",
        (
            "ApexVoiceSnapshot",
            "GateAction",
            "MetaSnapshot",
            "apex_gate",
            "apex_to_firm_payload",
            "apply_meta_overrides",
            "build_meta_context",
            "meta_to_firm_payload",
            "run_apex_evaluation",
            "run_meta_evaluation",
        ),
        (),  # __init__.py has no functions, just re-exports
        1500,
    ),
    (
        _HERE / "eta_v3" / "meta_adapter.py",
        "eta_v3_meta_adapter.py",
        (
            "MetaSnapshot",
            "build_meta_context",
            "run_meta_evaluation",
            "meta_to_firm_payload",
            "apply_meta_overrides",
            "summarize_meta",
            "probe_meta_firm_engine",
        ),
        # apply_meta_overrides is the function that got lopped off at
        # line 285 twice this session. Every function below must
        # reach a Return — if any doesn't, we're truncated again.
        (
            "build_meta_context",
            "run_meta_evaluation",
            "meta_to_firm_payload",
            "apply_meta_overrides",
            "summarize_meta",
            "probe_meta_firm_engine",
        ),
        8000,
    ),
    (
        # run_all_phases.py was truncated mid-function in v10 — the
        # REPORT_PATH.parent.mkdir(paren call at the tail was cut off.
        # Guard the script itself so future truncations self-heal.
        _REPO_ROOT / "scripts" / "run_all_phases.py",
        "run_all_phases.py",
        ("main", "_pre_run_shim_guard", "_render", "_run", "_stages"),
        ("main", "_render", "_run", "_stages"),
        10000,
    ),
    (
        # firm_live_review.py was truncated at line 294 during v10 —
        # the `lines.append(json.du` tail was cut off, SyntaxError on
        # parse. Guard it so a future OneDrive truncation self-heals.
        _REPO_ROOT / "scripts" / "firm_live_review.py",
        "firm_live_review.py",
        (
            "_derive_spec_payload",
            "_variant_side",
            "_derive_apex_snapshot",
            "_render_verdict",
            "main",
        ),
        (
            "_derive_spec_payload",
            "_variant_side",
            "_derive_apex_snapshot",
            "_render_verdict",
            "main",
        ),
        9000,
    ),
    (
        # test_eta_v3_meta_adapter.py was truncated mid-docstring in
        # the TestComposition class; pytest collection died on an
        # IndentationError at line 253. Guard the test file too — a
        # broken test module takes down the whole collection phase.
        _REPO_ROOT / "tests" / "level_1_unit" / "test_eta_v3_meta_adapter.py",
        "test_eta_v3_meta_adapter.py",
        (
            "_fake_snapshot",
            "TestProbe",
            "TestBuildContext",
            "TestRunEvaluation",
            "TestPayloadEnrichment",
            "TestApplyOverrides",
            "TestSummarize",
            "TestComposition",
        ),
        ("_fake_snapshot",),  # only the helper has a return; the rest are test classes
        10000,
    ),
)


def heal_all_guarded_files(*, raise_on_failure: bool = False) -> dict[str, ShimHealth]:
    """Run the full self-heal sweep — shim plus every guarded file.

    Returns a mapping from filename → final health. Useful for logs and
    the conftest summary line.
    """
    out: dict[str, ShimHealth] = {}
    # Shim first — most critical, historically the flakiest.
    out["firm_runtime.py"] = ensure_firm_runtime_healthy(
        raise_on_failure=raise_on_failure,
    )
    for target, fix_name, required, required_returns, min_bytes in GUARDED_FILES:
        known_good = _find_fix(fix_name)
        out[target.name] = ensure_file_healthy(
            target,
            known_good=known_good,
            required_symbols=required,
            required_fn_returns=required_returns,
            min_bytes=min_bytes,
            raise_on_failure=raise_on_failure,
        )
    return out
