"""Firm runtime shim — auto-generated by scripts/firm_bridge.py.

Do not edit by hand. This is the ONLY module in mnq_bot that imports the
external `firm` package; every other consumer goes through
``run_six_stage_review``. If the Firm code changes shape, rerun the bridge.

Generated at: 2026-04-26T04:23:59.481653+00:00
Bridge probe checksum: bf88d73c1a4a4e2f
"""
from __future__ import annotations

import sys
from dataclasses import asdict, is_dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

_FIRM_PACKAGE_PARENT = Path('C:\\Users\\edwar\\projects')
if str(_FIRM_PACKAGE_PARENT) not in sys.path:
    sys.path.insert(0, str(_FIRM_PACKAGE_PARENT))

from firm.agents.base import AgentInput as _AgentInput  # noqa: E402
from firm.agents.core import (  # noqa: E402
    MacroAgent,
    MicrostructureAgent,
    PMAgent,
    QuantAgent,
    RedTeamAgent,
    RiskManagerAgent,
)

_STAGES = (
    ("quant", QuantAgent),
    ("red_team", RedTeamAgent),
    ("risk", RiskManagerAgent),
    ("macro", MacroAgent),
    ("micro", MicrostructureAgent),
    ("pm", PMAgent),
)


def _safe_asdict(obj: Any) -> Any:
    if is_dataclass(obj):
        return {k: _safe_asdict(v) for k, v in asdict(obj).items()}
    if hasattr(obj, "value") and hasattr(type(obj), "__members__"):  # Enum
        return obj.value
    if isinstance(obj, (list, tuple)):
        return [_safe_asdict(v) for v in obj]
    if isinstance(obj, dict):
        return {k: _safe_asdict(v) for k, v in obj.items()}
    if isinstance(obj, datetime):
        return obj.isoformat()
    return obj


def compute_confluence(
    *,
    internals: dict[str, Any] | None = None,
    volatility: dict[str, Any] | None = None,
    cross_asset: dict[str, Any] | None = None,
    session: dict[str, Any] | None = None,
    micro: dict[str, Any] | None = None,
    calendar: dict[str, Any] | None = None,
    eta_v3: dict[str, Any] | None = None,
    regime: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Compute an 8-axis confluence snapshot.

    Fail-open stub: the upstream ``firm`` package does not yet expose a
    canonical ``compute_confluence``. This stub aggregates the inputs and
    returns a serializable dict so callers (e.g. ``firm_live_review``) can
    continue to operate and forward the snapshot to ``run_six_stage_review``
    without ImportError. When the real implementation lands upstream,
    regenerate the shim and this stub is superseded.
    """
    return {
        "internals": dict(internals or {}),
        "volatility": dict(volatility or {}),
        "cross_asset": dict(cross_asset or {}),
        "session": dict(session or {}),
        "micro": dict(micro or {}),
        "calendar": dict(calendar or {}),
        "eta_v3": dict(eta_v3 or {}),
        "regime": dict(regime or {}),
        "_stub": True,
    }


def run_six_stage_review(
    *,
    strategy_id: str,
    decision_context: str,
    payload: dict[str, Any],
    regime_snapshot: dict[str, Any] | None = None,
    confluence_result: dict[str, Any] | None = None,
    **_extra: Any,
) -> dict[str, Any]:
    """Run the six-stage adversarial review; return a serializable dict.

    Each stage receives the prior stage's output as ``prior_stage_output``.
    The PM stage additionally receives ``agent_outputs`` (raw AgentOutput
    objects) inside its payload, which is the contract its evaluate()
    method expects for dissent-tally + synthesis.

    ``confluence_result`` (optional): an 8-axis confluence dict produced by
    ``compute_confluence``. Currently folded into each stage's payload as
    ``confluence`` so agents can consult it; ignored if None.
    ``**_extra``: reserved for forward-compat — any future kwarg passed by
    the caller is silently accepted (and logged into payload as
    ``_extra_kwargs``) rather than raising TypeError.
    """
    prior: Any = None
    raw_outputs: dict[str, Any] = {}
    outputs: dict[str, Any] = {}
    for stage_name, cls in _STAGES:
        agent = cls()
        stage_payload = dict(payload)
        if confluence_result is not None:
            stage_payload["confluence"] = confluence_result
        if _extra:
            stage_payload["_extra_kwargs"] = dict(_extra)
        if stage_name == "pm":
            stage_payload["agent_outputs"] = raw_outputs
        in_ = _AgentInput(
            strategy_id=strategy_id,
            decision_context=decision_context,
            payload=stage_payload,
            prior_stage_output=_safe_asdict(prior) if prior is not None else None,
            regime_snapshot=regime_snapshot or {},
        )
        out = agent.evaluate(in_)
        raw_outputs[stage_name] = out
        outputs[stage_name] = _safe_asdict(out)
        prior = out
    return outputs


def record_trade_outcome(
    *,
    pnl_r: float,
    regime: str,
    **_extra: Any,
) -> dict[str, Any]:
    """Record a closed-trade outcome for the adaptive learner.

    B4 partial closure -- see scripts/firm_bridge.py SHIM_TEMPLATE
    for the canonical version. Editing this file directly does
    NOT survive the next bridge regen.
    """
    from datetime import UTC
    record: dict[str, Any] = {
        "ts_utc": datetime.now(UTC).isoformat(),
        "pnl_r": float(pnl_r),
        "regime": str(regime),
        "_stub": True,
    }
    if _extra:
        record["_extra"] = dict(_extra)
    try:
        from mnq.core.paths import REPO_ROOT
        journal_path = Path(REPO_ROOT) / "data" / "learner_journal.jsonl"
    except ImportError:
        journal_path = (
            Path(__file__).resolve().parent.parent.parent
            / "data" / "learner_journal.jsonl"
        )
    journal_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        import json
        with journal_path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(record) + "\n")
    except OSError:
        pass
    return record
