"""Firm runtime shim — auto-generated by scripts/firm_bridge.py.

Do not edit by hand. This is the ONLY module in mnq_bot that imports the
external `firm` package; every other consumer goes through
``run_six_stage_review``. If the Firm code changes shape, rerun the bridge.

Generated at: 2026-04-26T00:22:35.167229+00:00
Bridge probe checksum: 86ef94ad82b1dc1c
"""
from __future__ import annotations

import sys
from dataclasses import asdict, is_dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

# H2 closure (Red Team review 2026-04-25): firm package moved out of
# OneDrive. The OneDrive path used to truncate the firm_runtime.py shim
# unpredictably, which is why _shim_guard.py exists. Copy lives at
# ``C:/Users/edwar/projects/firm/`` (sibling to mnq_bot). Falls back to
# the OneDrive path if the projects copy is missing -- e.g. on a fresh
# machine that hasn't run the migration yet.
_FIRM_PACKAGE_PARENT = Path('C:\\Users\\edwar\\projects')
_FIRM_PACKAGE_FALLBACK = Path('C:\\Users\\edwar\\OneDrive\\The_Firm\\the_firm_complete\\desktop_app')
if not (_FIRM_PACKAGE_PARENT / 'firm').exists() and (_FIRM_PACKAGE_FALLBACK / 'firm').exists():
    _FIRM_PACKAGE_PARENT = _FIRM_PACKAGE_FALLBACK
if str(_FIRM_PACKAGE_PARENT) not in sys.path:
    sys.path.insert(0, str(_FIRM_PACKAGE_PARENT))

from firm.agents.base import AgentInput as _AgentInput  # noqa: E402
from firm.agents.core import (  # noqa: E402
    MacroAgent,
    MicrostructureAgent,
    PMAgent,
    QuantAgent,
    RedTeamAgent,
    RiskManagerAgent,
)

_STAGES = (
    ("quant", QuantAgent),
    ("red_team", RedTeamAgent),
    ("risk", RiskManagerAgent),
    ("macro", MacroAgent),
    ("micro", MicrostructureAgent),
    ("pm", PMAgent),
)


def _safe_asdict(obj: Any) -> Any:
    if is_dataclass(obj):
        return {k: _safe_asdict(v) for k, v in asdict(obj).items()}
    if hasattr(obj, "value") and hasattr(type(obj), "__members__"):  # Enum
        return obj.value
    if isinstance(obj, (list, tuple)):
        return [_safe_asdict(v) for v in obj]
    if isinstance(obj, dict):
        return {k: _safe_asdict(v) for k, v in obj.items()}
    if isinstance(obj, datetime):
        return obj.isoformat()
    return obj


def compute_confluence(
    *,
    internals: dict[str, Any] | None = None,
    volatility: dict[str, Any] | None = None,
    cross_asset: dict[str, Any] | None = None,
    session: dict[str, Any] | None = None,
    micro: dict[str, Any] | None = None,
    calendar: dict[str, Any] | None = None,
    eta_v3: dict[str, Any] | None = None,
    regime: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Compute an 8-axis confluence snapshot.

    Fail-open stub: the upstream ``firm`` package does not yet expose a
    canonical ``compute_confluence``. This stub aggregates the inputs and
    returns a serializable dict so callers (e.g. ``firm_live_review``) can
    continue to operate and forward the snapshot to ``run_six_stage_review``
    without ImportError. When the real implementation lands upstream,
    regenerate the shim and this stub is superseded.
    """
    return {
        "internals": dict(internals or {}),
        "volatility": dict(volatility or {}),
        "cross_asset": dict(cross_asset or {}),
        "session": dict(session or {}),
        "micro": dict(micro or {}),
        "calendar": dict(calendar or {}),
        "eta_v3": dict(eta_v3 or {}),
        "regime": dict(regime or {}),
        "_stub": True,
    }


def run_six_stage_review(
    *,
    strategy_id: str,
    decision_context: str,
    payload: dict[str, Any],
    regime_snapshot: dict[str, Any] | None = None,
    confluence_result: dict[str, Any] | None = None,
    **_extra: Any,
) -> dict[str, Any]:
    """Run the six-stage adversarial review; return a serializable dict.

    Each stage receives the prior stage's output as ``prior_stage_output``.
    The PM stage additionally receives ``agent_outputs`` (raw AgentOutput
    objects) inside its payload, which is the contract its evaluate()
    method expects for dissent-tally + synthesis.

    ``confluence_result`` (optional): an 8-axis confluence dict produced by
    ``compute_confluence``. Currently folded into each stage's payload as
    ``confluence`` so agents can consult it; ignored if None.
    ``**_extra``: reserved for forward-compat — any future kwarg passed by
    the caller is silently accepted (and logged into payload as
    ``_extra_kwargs``) rather than raising TypeError.
    """
    prior: Any = None
    raw_outputs: dict[str, Any] = {}
    outputs: dict[str, Any] = {}
    for stage_name, cls in _STAGES:
        agent = cls()
        stage_payload = dict(payload)
        if confluence_result is not None:
            stage_payload["confluence"] = confluence_result
        if _extra:
            stage_payload["_extra_kwargs"] = dict(_extra)
        if stage_name == "pm":
            stage_payload["agent_outputs"] = raw_outputs
        in_ = _AgentInput(
            strategy_id=strategy_id,
            decision_context=decision_context,
            payload=stage_payload,
            prior_stage_output=_safe_asdict(prior) if prior is not None else None,
            regime_snapshot=regime_snapshot or {},
        )
        out = agent.evaluate(in_)
        raw_outputs[stage_name] = out
        outputs[stage_name] = _safe_asdict(out)
        prior = out
    return outputs


def record_trade_outcome(
    *,
    pnl_r: float,
    regime: str,
    **_extra: Any,
) -> dict[str, Any]:
    """Record a closed-trade outcome for the adaptive learner.

    B4 partial closure (Red Team review 2026-04-25). The Red Team
    found that ``scripts/live_sim.py:337`` imports this name and the
    import was silently failing (``except (ImportError, Exception):
    pass``), so the adaptive-learner integration was a no-op for
    every closed trade -- "learner integrated" reports were lying.

    The full B4 closure (per-bar Firm review on real tape, plus
    moving the firm package out of OneDrive) is a v0.2.x design
    call. This stub:

      * makes the import succeed so the silent-fail stops happening,
      * appends the outcome to ``data/learner_journal.jsonl`` so
        the operator has a paper trail,
      * returns a dict the caller can log if it wants to.

    The stub does NOT call the real Firm package's adaptive learner
    -- that integration is M2-shaped and gated on the same H1
    calibration empirics that gate KillVerdict-on-drift synthesis.
    Until then this is observation-only.

    Lands when: the Firm package's adaptive learner is reachable
    via firm_bridge AND a per-trade learner-update path is wired,
    AND a test asserts the journal entry triggers a learner
    state-change.
    """
    from datetime import UTC, datetime
    from pathlib import Path

    record: dict[str, Any] = {
        "ts_utc": datetime.now(UTC).isoformat(),
        "pnl_r": float(pnl_r),
        "regime": str(regime),
        "_stub": True,  # remove when real learner is wired
    }
    if _extra:
        record["_extra"] = dict(_extra)

    # Append to a journal file alongside the existing event-source
    # journal. Use the canonical mnq.core.paths location when
    # available; otherwise fall back to a repo-relative path that the
    # operator can grep.
    try:
        from mnq.core.paths import REPO_ROOT  # type: ignore[import-not-found]
        journal_path = Path(REPO_ROOT) / "data" / "learner_journal.jsonl"
    except ImportError:
        journal_path = (
            Path(__file__).resolve().parent.parent.parent
            / "data" / "learner_journal.jsonl"
        )
    journal_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        import json
        with journal_path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(record) + "\n")
    except OSError:
        # Fail open: an unwriteable journal must not break the
        # caller. The Red Team finding is "silent failure"; this
        # stub at minimum returns a structured record the caller
        # can log to its own observability layer.
        pass
    return record
