"""Firm runtime shim — auto-generated by scripts/firm_bridge.py.

Do not edit by hand. This is the ONLY module in mnq_bot that imports the
external `firm` package; every other consumer goes through
``run_six_stage_review``. If the Firm code changes shape, rerun the bridge.

Intelligence layer upgrade: now passes confluence_result and learner_weights
through the full 6-stage pipeline, using NQConfluenceEngine + NQAdaptiveLearner.

Generated at: 2026-04-16T21:59:37.182258+00:00
Bridge probe checksum: fb5b09d867a28cfd
"""
from __future__ import annotations

import sys
from dataclasses import asdict, is_dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

_FIRM_PACKAGE_PARENT = Path('C:/Users/edwar/OneDrive/The_Firm/the_firm_complete/desktop_app')
if str(_FIRM_PACKAGE_PARENT) not in sys.path:
    sys.path.insert(0, str(_FIRM_PACKAGE_PARENT))

from firm.agents.base import AgentInput as _AgentInput  # noqa: E402
from firm.agents.core import (  # noqa: E402
    MacroAgent,
    MicrostructureAgent,
    PMAgent,
    QuantAgent,
    RedTeamAgent,
    RiskManagerAgent,
)

# Intelligence layer imports
try:
    from firm.intelligence.confluence import NQConfluenceEngine, NQConfluenceResult  # noqa: E402
    from firm.intelligence.learner import NQAdaptiveLearner  # noqa: E402
    _INTELLIGENCE_AVAILABLE = True
except ImportError:
    _INTELLIGENCE_AVAILABLE = False

_STAGES = (
    ("quant", QuantAgent),
    ("red_team", RedTeamAgent),
    ("risk", RiskManagerAgent),
    ("macro", MacroAgent),
    ("micro", MicrostructureAgent),
    ("pm", PMAgent),
)

# Module-level singletons — persist across calls within a session
_confluence_engine: Optional["NQConfluenceEngine"] = None
_adaptive_learner: Optional["NQAdaptiveLearner"] = None


def _get_confluence_engine() -> Optional["NQConfluenceEngine"]:
    global _confluence_engine
    if not _INTELLIGENCE_AVAILABLE:
        return None
    if _confluence_engine is None:
        _confluence_engine = NQConfluenceEngine()
    return _confluence_engine


def _get_learner() -> Optional["NQAdaptiveLearner"]:
    global _adaptive_learner
    if not _INTELLIGENCE_AVAILABLE:
        return None
    if _adaptive_learner is None:
        _adaptive_learner = NQAdaptiveLearner()
    return _adaptive_learner


def _safe_asdict(obj: Any) -> Any:
    if is_dataclass(obj):
        return {k: _safe_asdict(v) for k, v in asdict(obj).items()}
    if hasattr(obj, "value") and hasattr(type(obj), "__members__"):  # Enum
        return obj.value
    if isinstance(obj, (list, tuple)):
        return [_safe_asdict(v) for v in obj]
    if isinstance(obj, dict):
        return {k: _safe_asdict(v) for k, v in obj.items()}
    if isinstance(obj, datetime):
        return obj.isoformat()
    return obj


def compute_confluence(
    *,
    internals: dict | None = None,
    volatility: dict | None = None,
    cross_asset: dict | None = None,
    session: dict | None = None,
    micro: dict | None = None,
    calendar: dict | None = None,
    eta_v3: dict | None = None,
    regime: dict | None = None,
) -> Optional["NQConfluenceResult"]:
    """Compute 8-axis confluence score for the current market state.

    Returns NQConfluenceResult or None if intelligence layer unavailable.
    This is the primary entry point for mnq_bot to get a confluence reading
    before calling run_six_stage_review.
    """
    engine = _get_confluence_engine()
    if engine is None:
        return None

    # Sync learner weights into engine
    learner = _get_learner()
    if learner is not None:
        learned = learner.get_axis_weights()
        if learned:
            engine.set_weights(learned)

    return engine.score(
        internals=internals,
        volatility=volatility,
        cross_asset=cross_asset,
        session=session,
        micro=micro,
        calendar=calendar,
        eta_v3=eta_v3,
        regime=regime,
    )


def compute_adjusted_size(
    confluence_result: Any,
    *,
    recent_pnl_r: float = 0.0,
    consecutive_losses: int = 0,
    dd_from_peak_r: float = 0.0,
) -> float:
    """Compute drawdown-adjusted position size multiplier.

    Wraps the confluence engine's drawdown_adjusted_size method.
    Returns a float multiplier (0.1 to 1.5) that should be applied
    to the base position size.

    This is the profit-maximizer: bet big when aligned, shrink fast
    when in a drawdown or on a losing streak.
    """
    engine = _get_confluence_engine()
    if engine is None or confluence_result is None:
        return 1.0
    return engine.drawdown_adjusted_size(
        confluence_result,
        recent_pnl_r=recent_pnl_r,
        consecutive_losses=consecutive_losses,
        dd_from_peak_r=dd_from_peak_r,
    )


def record_trade_outcome(
    pnl_r: float,
    axis_scores: dict | None = None,
    agent_verdicts: dict | None = None,
    regime: str = "",
) -> None:
    """Record a trade outcome for adaptive learning.

    Called after each trade closes so the learner can adjust axis
    and agent weights for future confluence scoring.
    """
    learner = _get_learner()
    if learner is not None:
        learner.record_trade(
            pnl_r=pnl_r,
            axis_scores=axis_scores,
            agent_verdicts=agent_verdicts,
            regime=regime,
        )


def run_six_stage_review(
    *,
    strategy_id: str,
    decision_context: str,
    payload: dict[str, Any],
    regime_snapshot: dict[str, Any] | None = None,
    confluence_result: Any | None = None,
) -> dict[str, Any]:
    """Run the six-stage adversarial review; return a serializable dict.

    Each stage receives the prior stage's output as ``prior_stage_output``.
    The PM stage additionally receives ``agent_outputs`` (raw AgentOutput
    objects) inside its payload, which is the contract its evaluate()
    method expects for dissent-tally + synthesis.

    Intelligence layer: when confluence_result is provided, it is passed
    to every agent along with the current learner weights. This enables
    confluence-modulated sizing, CONFLICTED→HOLD gating, and adaptive
    probability adjustment across the full pipeline.
    """
    # Get learner weights for this review cycle
    learner = _get_learner()
    learner_weights = None
    if learner is not None:
        learner_weights = {
            "axis_weights": learner.get_axis_weights(),
            "agent_weights": learner.get_agent_weights(),
        }

    prior: Any = None
    raw_outputs: dict[str, Any] = {}
    outputs: dict[str, Any] = {}
    for stage_name, cls in _STAGES:
        agent = cls()
        stage_payload = dict(payload)
        if stage_name == "pm":
            stage_payload["agent_outputs"] = raw_outputs
        in_ = _AgentInput(
            strategy_id=strategy_id,
            decision_context=decision_context,
            payload=stage_payload,
            prior_stage_output=_safe_asdict(prior) if prior is not None else None,
            regime_snapshot=regime_snapshot or {},
            confluence_result=confluence_result,
            learner_weights=learner_weights,
        )
        out = agent.evaluate(in_)
        raw_outputs[stage_name] = out
        outputs[stage_name] = _safe_asdict(out)
        prior = out
    return outputs


def get_intelligence_status() -> dict[str, Any]:
    """Return intelligence layer status for diagnostics."""
    if not _INTELLIGENCE_AVAILABLE:
        return {"available": False, "reason": "Intelligence layer not importable"}
    learner = _get_learner()
    return {
        "available": True,
        "engine": "NQConfluenceEngine (8-axis)",
        "learner": learner.status() if learner else None,
        "axes": [
            "MARKET_INTERNALS", "VOLATILITY", "CROSS_ASSET", "SESSION_TIMING",
            "MICROSTRUCTURE", "MACRO_CALENDAR", "APEX_V3_VOICES", "REGIME_MOMENTUM",
        ],
    }
