"""[REAL] Ship manifest — hard gate between "variant exists" and "can go live".

Operationalizes the ``scripts/edge_forensics.py`` conclusion. That script
runs five decomposition lenses (quarterly equity, regime split, Deflated
Sharpe @ 30 / 100 trials, 10k bootstrap CI, cost sensitivity) and writes
``reports/edge_forensics.json`` with a per-variant verdict:

    PASS    — statistically significant, cost-survivable, stable across
              buckets.
    WATCH   — passes core tests, one yellow flag (mild Sharpe, late-bucket
              softness, etc.).
    FRAGILE — two yellow flags — trade with monitoring only.
    FAIL    — one fatal flag (e.g. CI covers zero).
    KILL    — two or more fatal flags — never ship.

``ShipManifest.is_shippable(name)`` returns True only for ``PASS`` and
``WATCH``. Any live-path code that consults the manifest before routing a
strategy is guaranteed never to ship a ``FAIL`` or ``KILL`` variant.

The manifest is intentionally read-only — it reflects the state of the
forensics artifact at a point in time and is regenerated by rerunning
``scripts/edge_forensics.py``. The ``generated`` timestamp on the JSON
payload lets consumers detect a stale manifest.

Usage:

    from mnq.gauntlet.ship_manifest import ShipManifest, ShipManifestError

    manifest = ShipManifest.from_default_path()
    if not manifest.is_shippable("orb_only_pm30"):
        raise RuntimeError("variant not cleared to ship")

    # For enforcement as a gate
    for name in live_variants:
        manifest.require_shippable(name)

The production promotion pipeline calls ``require_shippable`` on every
variant it's about to route to a live venue, and refuses to start if any
fails.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Final

_REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[3]
DEFAULT_MANIFEST_PATH: Final[Path] = _REPO_ROOT / "reports" / "edge_forensics.json"

SHIPPABLE_VERDICTS: Final[frozenset[str]] = frozenset({"PASS", "WATCH"})
KNOWN_VERDICTS: Final[frozenset[str]] = frozenset(
    {
        "PASS",
        "WATCH",
        "FRAGILE",
        "FAIL",
        "KILL",
    }
)


class ShipManifestError(Exception):
    """Raised when a caller tries to ship a variant that is not cleared."""


class ShipManifestMissingError(ShipManifestError):
    """Raised when the manifest file does not exist at the expected path."""


class ShipManifestSchemaError(ShipManifestError):
    """Raised when the manifest JSON is missing required fields."""


@dataclass(frozen=True, slots=True)
class VariantVerdict:
    """A single variant's entry in the manifest (immutable snapshot).

    Only the fields we gate on are pulled out as named attributes; the
    raw dict is preserved for tearsheet / debug use.
    """

    variant: str
    verdict: str
    shippable: bool
    n_trades: int
    sharpe: float
    dsr_100: float
    bootstrap_lo: float
    bootstrap_hi: float
    bootstrap_ci_covers_zero: bool
    cost_sensitivity: dict[str, float]
    reasons: tuple[str, ...]
    raw: dict

    @classmethod
    def from_dict(cls, name: str, d: dict) -> VariantVerdict:
        verdict = d.get("verdict")
        if verdict not in KNOWN_VERDICTS:
            raise ShipManifestSchemaError(f"variant {name!r}: unknown verdict {verdict!r}")
        shippable_flag = bool(d.get("shippable", False))
        # Invariant: shippable == (verdict in SHIPPABLE_VERDICTS).
        expected = verdict in SHIPPABLE_VERDICTS
        if shippable_flag != expected:
            raise ShipManifestSchemaError(
                f"variant {name!r}: shippable={shippable_flag!r} disagrees with "
                f"verdict={verdict!r} (expected {expected})"
            )
        cost = d.get("cost_sensitivity", {})
        if not isinstance(cost, dict):
            raise ShipManifestSchemaError(
                f"variant {name!r}: cost_sensitivity must be dict, got {type(cost).__name__}"
            )
        return cls(
            variant=name,
            verdict=str(verdict),
            shippable=shippable_flag,
            n_trades=int(d.get("n_trades", 0)),
            sharpe=float(d.get("sharpe", 0.0)),
            dsr_100=float(d.get("dsr_100", 0.0)),
            bootstrap_lo=float(d.get("bootstrap_lo", 0.0)),
            bootstrap_hi=float(d.get("bootstrap_hi", 0.0)),
            bootstrap_ci_covers_zero=bool(d.get("bootstrap_ci_covers_zero", True)),
            cost_sensitivity={str(k): float(v) for k, v in cost.items()},
            reasons=tuple(d.get("reasons", [])),
            raw=d,
        )


@dataclass(frozen=True, slots=True)
class ShipManifest:
    """Read-only view of ``reports/edge_forensics.json``."""

    generated: str
    bootstrap_iters: int
    n_buckets: int
    cost_scenarios_per_trade: tuple[float, ...]
    counts: dict[str, int]
    variants: dict[str, VariantVerdict]
    source_path: Path

    # ------------------------------------------------------------------
    # Constructors
    # ------------------------------------------------------------------
    @classmethod
    def from_default_path(cls) -> ShipManifest:
        """Load the manifest from the canonical location in ``reports/``."""
        return cls.from_path(DEFAULT_MANIFEST_PATH)

    @classmethod
    def from_path(cls, path: Path) -> ShipManifest:
        """Load the manifest from an explicit path (useful for tests)."""
        path = Path(path)
        if not path.exists():
            raise ShipManifestMissingError(
                f"ship manifest not found at {path}; run scripts/edge_forensics.py first"
            )
        try:
            payload = json.loads(path.read_text())
        except json.JSONDecodeError as e:
            raise ShipManifestSchemaError(f"manifest {path} is not valid JSON: {e}") from e
        return cls.from_dict(payload, source_path=path)

    @classmethod
    def from_dict(cls, payload: dict, *, source_path: Path | None = None) -> ShipManifest:
        """Build directly from a parsed dict — used by ``from_path`` + tests."""
        for req in ("generated", "bootstrap_iters", "n_buckets", "variants"):
            if req not in payload:
                raise ShipManifestSchemaError(f"manifest missing required field: {req!r}")
        raw_variants = payload.get("variants", {})
        if not isinstance(raw_variants, dict):
            raise ShipManifestSchemaError("manifest.variants must be a dict")
        parsed: dict[str, VariantVerdict] = {
            name: VariantVerdict.from_dict(name, d) for name, d in raw_variants.items()
        }
        counts = payload.get("counts", {})
        if not isinstance(counts, dict):
            raise ShipManifestSchemaError("manifest.counts must be a dict")
        return cls(
            generated=str(payload["generated"]),
            bootstrap_iters=int(payload["bootstrap_iters"]),
            n_buckets=int(payload["n_buckets"]),
            cost_scenarios_per_trade=tuple(
                float(x) for x in payload.get("cost_scenarios_per_trade", ())
            ),
            counts={str(k): int(v) for k, v in counts.items()},
            variants=parsed,
            source_path=Path(source_path) if source_path else Path(),
        )

    # ------------------------------------------------------------------
    # Core queries — the reason this module exists
    # ------------------------------------------------------------------
    def is_shippable(self, variant: str) -> bool:
        """True iff ``variant`` is registered AND its verdict is PASS or WATCH.

        Unknown variants return False. That's the safe default — if you
        haven't proven the edge, you can't ship it.
        """
        entry = self.variants.get(variant)
        if entry is None:
            return False
        return entry.shippable

    def verdict_for(self, variant: str) -> str:
        """Return the verdict string for ``variant`` (``UNKNOWN`` if absent)."""
        entry = self.variants.get(variant)
        return entry.verdict if entry is not None else "UNKNOWN"

    def require_shippable(self, variant: str) -> VariantVerdict:
        """Raise ``ShipManifestError`` unless the variant is cleared.

        Return the VariantVerdict so the caller can log or telemetry on
        the shipping fields (Sharpe, DSR, etc.).
        """
        entry = self.variants.get(variant)
        if entry is None:
            raise ShipManifestError(
                f"variant {variant!r} is not in the ship manifest — "
                f"run edge_forensics and confirm it was analyzed"
            )
        if not entry.shippable:
            raise ShipManifestError(
                f"variant {variant!r} verdict = {entry.verdict!r}; not cleared to ship. "
                f"Reasons: {'; '.join(entry.reasons) if entry.reasons else 'n/a'}"
            )
        return entry

    # ------------------------------------------------------------------
    # Bulk views
    # ------------------------------------------------------------------
    def shippable_variants(self) -> list[str]:
        """Sorted list of all variant names cleared to ship."""
        return sorted(name for name, v in self.variants.items() if v.shippable)

    def killed_variants(self) -> list[str]:
        """Sorted list of all variant names with verdict == KILL."""
        return sorted(name for name, v in self.variants.items() if v.verdict == "KILL")

    def __len__(self) -> int:
        return len(self.variants)

    def __contains__(self, variant: object) -> bool:
        return isinstance(variant, str) and variant in self.variants


__all__ = [
    "DEFAULT_MANIFEST_PATH",
    "KNOWN_VERDICTS",
    "SHIPPABLE_VERDICTS",
    "ShipManifest",
    "ShipManifestError",
    "ShipManifestMissingError",
    "ShipManifestSchemaError",
    "VariantVerdict",
]
